name: Build Container Disk

on:
  schedule:
    - cron: '0 0 * * *'
      timezone: "UTC"
  workflow_dispatch:
    inputs:
      k8s_version:
        description: 'Kubernetes version'
        required: true
        default: '1.36.2'
      k8s_deb_revision:
        description: 'Package revision suffix'
        required: true
        default: '2.1'
      crictl_version:
        description: 'crictl version'
        required: true
        default: '1.36.0'
      registry:
        description: 'Registry path'
        required: true
        default: 'ghcr.io/r3m8'
      ubuntu_version:
        description: 'Ubuntu version'
        required: true
        default: '2604'

jobs:
  build:
    runs-on: ubuntu-26.04
    permissions:
      contents: read
      packages: write
    env:
      CAPI_DIR: ${{ github.workspace }}/image-builder/images/capi
      IMAGE_BUILDER_VERSION: 'main'
      K8S_VERSION: ${{ inputs.k8s_version || '1.36.2' }}
      K8S_DEB_REVISION: ${{ inputs.k8s_deb_revision || '2.1' }}
      CRICTL_VERSION: ${{ inputs.crictl_version || '1.36.0' }}
      REGISTRY: ${{ inputs.registry || 'ghcr.io/r3m8' }}
      UBUNTU_VERSION: ${{ inputs.ubuntu_version || '2604' }}
      IMAGE: ${{ inputs.registry || 'ghcr.io/r3m8' }}/ubuntu-${{ inputs.ubuntu_version || '2604' }}-container-disk
    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y qemu-system-x86 wget unzip python3 python3-pip curl
          sudo chmod 666 /dev/kvm

      - name: Clone image-builder
        run: git clone -b ${{ env.IMAGE_BUILDER_VERSION }} https://github.com/kubernetes-sigs/image-builder.git ${{ github.workspace }}/image-builder

      - name: k8s version override
        working-directory: ${{ env.CAPI_DIR }}
        env:
          VERSION: ${{ env.K8S_VERSION }}
        run: |
          cat > k8s-override.json <<EOF
          {
            "kubernetes_semver": "v${VERSION}",
            "kubernetes_series": "v${VERSION%.*}",
            "kubernetes_deb_version": "${VERSION}-${{ env.K8S_DEB_REVISION }}",
            "kubernetes_rpm_version": "${VERSION}",
            "crictl_version": "${{ env.CRICTL_VERSION }}"
          }
          EOF

      - name: Build image
        working-directory: ${{ env.CAPI_DIR }}
        env:
          PACKER_LOG: 1
          PACKER_VAR_FILES: ${{ env.CAPI_DIR }}/k8s-override.json
        run: |
          make deps-qemu
          make build-kubevirt-qemu-ubuntu-${{ env.UBUNTU_VERSION }}

      - name: Container metadata
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ${{ env.IMAGE }}
          tags: |
            type=raw,value=v${{ env.K8S_VERSION }}-{{date 'YYYYMMDD'}}
            type=raw,value=v${{ env.K8S_VERSION }}
            type=raw,value=latest

      - name: Log in to registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image
        uses: docker/build-push-action@v7
        with:
          context: ${{ env.CAPI_DIR }}/output/ubuntu-${{ env.UBUNTU_VERSION }}-kube-v${{ env.K8S_VERSION }}
          file: ${{ env.CAPI_DIR }}/output/ubuntu-${{ env.UBUNTU_VERSION }}-kube-v${{ env.K8S_VERSION }}/kubevirt-Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}